assets/images/quest-builder.svg, index.md
Use a local asset for the quest builder index
=> fix: update index picture

docs/building-your-quest/writing-quest-texts/message-components.md
Remove unused array on `components`, and fixed the indentation accordingly
=> fix: message components example indentation

docs/building-your-quest/creating-steps.md
Duplicates #25 and #26, but solving using Jekyll's link command to prevent broken links in the future.
=> fix: broken links

docs/building-your-quest/triggers-and-payloads.md
Adding docs for the user event trigger
=> Add user event

docs/building-your-quest/conditions.md, docs/building-your-quest/conditions/github_does_file_contain.md, docs/building-your-quest/triggers-and-payloads.md
Fix documentarians - github_is_file_contains to github_does_file_contain
=> fix typo - github_is_file_contains tp github_does_file_contain

docs/building-your-quest/index.md
This PR will fix a typo on the Quest Builder Docs.
=> Fix typo error

docs/building-your-quest/conditions/text-match-regex.md
Ran into this while working on my quest, so updating the docs to capture this param for future reference.
=> Add flags params to the text_match_regex docs

docs/building-your-quest/triggers-and-payloads.md
Add and example for github_pr_lifecycle_status trigger
=> github_pr_lifecycle_status trigger

docs/building-your-quest/writing-quest-texts/index.md
Added guidelines for the title, the tagline, and the quest descriptions.
=> New guidelines for quest descriptions.

docs/building-your-quest/conditions/github-is-file-added-in-push.md
Missing some info, especially regarding the params
=> Add docs to github_is_file_added_in_push

docs/building-your-quest/index.md
Update the documentation for missing fields:
- Summary on the quest
=> Missing quests field

docs/building-your-quest/index.md
Add missing shouldResetRepo documentation
=> Add shouldResetRepo prop

docs/building-your-quest/actions/bot-message.md, docs/building-your-quest/actions/finish-step.md, docs/building-your-quest/actions/github-commit-file.md, docs/building-your-quest/actions/github-create-repo.md, docs/building-your-quest/actions/github-invite-user.md, docs/building-your-quest/actions/github-open-issue.md, docs/building-your-quest/actions/github-pr-approve.md, docs/building-your-quest/actions/github-pr-comment.md, docs/building-your-quest/actions/github-pr-reject.md, docs/building-your-quest/actions/network-http-request.md, docs/building-your-quest/actions/newrelic-configure-with-key.md, docs/building-your-quest/actions/quest-notification.md
The pages didn't match the order of the table in the index.md file. They have been reorganized to match.
=> Ordered Pages in the Actions Sub-Menu

docs/building-your-quest/flow-nodes.md, docs/building-your-quest/github-actions.md, docs/building-your-quest/index.md, docs/building-your-quest/quest-resources/index.md, docs/building-your-quest/quest-resources/k8s.md, docs/building-your-quest/quest-resources/user.md
Edited flow nodes, github actions, quest resources. (Supported skills did not need to be edited). Numbered the Quest Resource pages.
=> Editing sdk

docs/building-your-quest/creating-steps.md
Added point-per-step requirement and character limit
=> Adding info about "What you'll learn"

docs/building-your-quest/actions/finish-step.md, docs/building-your-quest/actions/index.md, docs/building-your-quest/actions/network-find-selector.md, docs/building-your-quest/actions/network-http-load.md, docs/building-your-quest/actions/quest-notification.md
Adding documentation for two missing actions:
network_http_load
network_find_selector
=> add missing network actions

docs/building-your-quest/triggers-and-payloads.md
I'm sure if I'm referencing the right thing for ping, the use case is unclear to me.
=> typos + missing links in triggers-and-payloads

_includes/head_custom.html, docs/building-your-quest/conditions/action-success.md, docs/building-your-quest/conditions/array-every.md, docs/building-your-quest/conditions/array-find.md, docs/building-your-quest/conditions/database-check-connection-url.md, docs/building-your-quest/conditions/github-is-file-added-in-push.md, docs/building-your-quest/conditions/github-is-file-added.md, docs/building-your-quest/conditions/github-is-file-modified.md, docs/building-your-quest/conditions/github-is-one-of-files-modified.md, docs/building-your-quest/conditions/github-is-repo-collaborator.md, docs/building-your-quest/conditions/github-is-user-valid.md, docs/building-your-quest/conditions/github_does_file_contain.md, docs/building-your-quest/conditions/is-falsy.md, docs/building-your-quest/conditions/is-truthy.md, docs/building-your-quest/conditions/is-user-message-text-ready-to-continue.md, docs/building-your-quest/conditions/k8s-backend-config-var-defined.md, docs/building-your-quest/conditions/k8s-secret-defined.md, docs/building-your-quest/conditions/newrelic-license-key-valid.md, docs/building-your-quest/conditions/text-contains-strings.md, docs/building-your-quest/conditions/text-match-regex.md, docs/building-your-quest/conditions/user-check-authentication-exists.md, docs/building-your-quest/index.md
Edited flow nodes, github actions, quest resources. (Supported skills did not need to be edited). Numbered the Quest Resource pages.
=> Editing sdk conditions

docs/building-your-quest/actions/finish-step.md, docs/building-your-quest/actions/github-add-secret.md, docs/building-your-quest/actions/index.md, docs/building-your-quest/actions/network-find-selector.md, docs/building-your-quest/actions/network-http-load.md, docs/building-your-quest/actions/network-http-request.md, docs/building-your-quest/actions/newrelic-configure-with-key.md, docs/building-your-quest/actions/quest-notification.md
Adds the `github_add_secret` action to the actions section
=> feat: add `github_add_secret` action

docs/building-your-quest/assets.md, docs/building-your-quest/index.md, docs/submitting-your-quest-for-review/graphic-design-guidelines.md, docs/submitting-your-quest-for-review/quest-submission-checklist.md
=> Remove logo

docs/building-your-quest/actions/index.md, docs/building-your-quest/actions/store-user-property.md
Add a new action to save a value under the user, so you'll be able to use it later.
=> Store user property action

docs/building-your-quest/index.md
Remove shouldResetRepo as it's not in use anymore
=> Remove `shouldResetRepo` as it's not in use anymore

docs/building-your-quest/creating-steps.md
Info about the default step `codespace_start_docker_compose` which prompts the users to open their codespace
=> default docker compose step

_config.yml
=> update copyright year

docs/building-your-quest/actions/github-reply-to-discussion.md, docs/building-your-quest/actions/github-repo-api.md, docs/building-your-quest/actions/index.md, docs/building-your-quest/triggers-and-payloads.md
add new github triggers and actions
=> feat: add new github triggers and actions

docs/building-your-quest/actions/github-reply-to-discussion.md, docs/building-your-quest/actions/github-repo-api.md, docs/building-your-quest/triggers-and-payloads.md
=> fix: some docs fixes

docs/building-your-quest/actions/index.md
=> fix: broken link

docs/building-your-quest/actions/github-pr-review.md
=> feat: pr review action
